import { div } from "framer-motion/client";
import React from "react";

function Content() {
    // const SEC = [
    //     {title:"",content:"This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator. "},
    //     {title:"Interpretation and Definitions",content:"Interpretation The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. Definitions For the purposes of this Privacy Policy: * 		Account means a unique account created for You to access our Service or parts of our Service. * 		Affiliate means an entity that controls, is controlled by or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. * 		Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Sukoon Edu Foundation. * 		Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. * 		Country refers to: India * 		Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. * 		Personal Data is any information that relates to an identified or identifiable individual. * 		Service refers to the Website. * 		Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. * 		Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service. * 		Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). * 		Website refers to Sukoon Edu Foundation, accessible from https://sukoon-edu.vercel.app/ * 		You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. "},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},

    // ]
  return (
    <div className="w-[90%] max-w-[1200px] mx-auto py-14">
      {/* <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1> */}
      <p className="mb-4">Last updated: January 01, 2025</p>
      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p className="mb-4">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Interpretation and Definitions</h2>
      <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
      <p className="mb-4">
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3 className="text-xl font-semibold mb-2">Definitions</h3>
      <ul className="list-disc list-inside mb-4">
        <li><strong>Account:</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate:</strong> means an entity that controls, is controlled by or is under common control with a party.</li>
        <li><strong>Company:</strong> refers to Sukoon Edu Foundation.</li>
        <li><strong>Cookies:</strong> small files placed on Your device by a website.</li>
        <li><strong>Country:</strong> refers to India.</li>
        <li><strong>Device:</strong> means any device that can access the Service.</li>
        <li><strong>Personal Data:</strong> any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service:</strong> refers to the Website.</li>
        <li><strong>Service Provider:</strong> any natural or legal person who processes the data on behalf of the Company.</li>
        <li><strong>Third-party Social Media Service:</strong> any website or social network through which a User can log in or create an account.</li>
        <li><strong>Usage Data:</strong> data collected automatically when using the Service.</li>
        <li><strong>Website:</strong> refers to Sukoon Edu Foundation, accessible from <a href="https://sukoon-edu.vercel.app/" className="text-blue-500">https://sukoon-edu.vercel.app/</a>.</li>
        <li><strong>You:</strong> the individual accessing or using the Service.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Collecting and Using Your Personal Data</h2>
      <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>
      <h4 className="font-semibold mb-2">Personal Data</h4>
      <p className="mb-4">
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="font-semibold mb-2">Usage Data</h4>
      <p className="mb-4">
        Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address, browser type, browser version, the pages of our Service that You visit, and other diagnostic data.
      </p>

      <h3 className="text-xl font-semibold mb-2">Information from Third-Party Social Media Services</h3>
      <p className="mb-4">
        The Company allows You to create an account and log in to use the Service through various Third-party Social Media Services such as Google, Facebook, Instagram, Twitter, and LinkedIn.
      </p>

    <h3 className="text-xl font-semibold mb-2">Tracking Technologies and Cookies</h3>
      <p className="mb-4">
        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
      </p>
      <ul className="list-disc list-inside mb-4">
        <li><strong>Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
        <li><strong>Web Beacons:</strong> Small electronic files that permit the Company to count users who have visited those pages or opened an email.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Use of Your Personal Data</h2>
      <p className="mb-4">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>To provide and maintain our Service.</li>
        <li>To manage Your Account.</li>
        <li>For the performance of a contract.</li>
        <li>To contact You.</li>
        <li>To provide You with news and special offers.</li>
        <li>To manage Your requests.</li>
        <li>For business transfers.</li>
        <li>For other purposes such as data analysis and improving our Service.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Retention of Your Personal Data</h2>
      <p className="mb-4">
        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Transfer of Your Personal Data</h2>
      <p className="mb-4">
        Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of Your jurisdiction.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Delete Your Personal Data</h2>
      <p className="mb-4">
        You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Disclosure of Your Personal Data</h2>
      <p className="mb-4">
        The Company may disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation or protect the rights of the Company.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Security of Your Personal Data</h2>
      <p className="mb-4">
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Children's Privacy</h2>
      <p className="mb-4">
        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Links to Other Websites</h2>
      <p className="mb-4">
        Our Service may contain links to other websites that are not operated by Us. We have no control over and assume no responsibility for the content or privacy policies of any third-party sites.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Changes to this Privacy Policy</h2>
      <p className="mb-4">
        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Contact Us</h2>
      <p className="mb-4">
        If you have any questions about this Privacy Policy, You can contact us by email: <a href="mailto:connect@mysukoon.in" className="text-blue-500">connect@mysuk oon.in</a>.
      </p>
    </div>
  );
}

export default Content;
