import { div } from "framer-motion/client";
import React from "react";

function Content() {
    // const SEC = [
    //     {title:"",content:"This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator. "},
    //     {title:"Interpretation and Definitions",content:"Interpretation The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. Definitions For the purposes of this Privacy Policy: * 		Account means a unique account created for You to access our Service or parts of our Service. * 		Affiliate means an entity that controls, is controlled by or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. * 		Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Sukoon Edu Foundation. * 		Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. * 		Country refers to: India * 		Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. * 		Personal Data is any information that relates to an identified or identifiable individual. * 		Service refers to the Website. * 		Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. * 		Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service. * 		Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). * 		Website refers to Sukoon Edu Foundation, accessible from https://sukoon-edu.vercel.app/ * 		You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. "},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},

    // ]
  return (
    <div className="w-[90%] max-w-[1200px] mx-auto py-14">
      {/* <h1 className="text-3xl font-bold mb-4">Refund Policy</h1> */}
      <p className="mb-4">Last updated: January 01, 2025</p>
      <p className="mb-4">
        At Sukoon Edu Village, fees and other payments may require you to request a refund. This Refund Policy outlines the process and conditions for refunding donations.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Refund Requests</h2>
      <p className="mb-4">
        If you wish to request a refund for your donation, please contact us at <a href="mailto:accounts@mysukoon.in" className="text-blue-500">accounts@mysukoon.in</a> within 7 days of making the donation. Please provide your name, Payment reference number (Bank Transaction), and a brief explanation for the refund request.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Refund Processing</h2>
      <ol className="list-decimal list-inside mb-4">
        <li><strong>Eligible Donations:</strong> Refunds are generally available for all types of payments made through our website or other channels.</li>
        <li><strong>Processing Time:</strong> We strive to process all eligible refund requests within 7-10 business days from the date of receipt. However, please note that the actual refund processing time may vary depending on your payment method and financial institution.</li>
        <li><strong>Refund Method:</strong> Refunds will be issued using the same payment method as the original payment, unless otherwise agreed upon or if the original payment method is no longer valid or available.</li>
        <li><strong>Refund Fees:</strong> In some cases, additional fees or charges imposed by payment gateways or financial institutions may be deducted from the refund amount. Sukoon Edu Foundation is not responsible for any such fees or charges.</li>
      </ol>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Privacy Policy</h2>
      <p className="mb-4">
        We may collect and use your information in accordance with our Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Contact Us</h2>
      <p className="mb-4">
        If you have any questions or concerns about our Refund Policy or need assistance with a refund request, please contact us at <a href="mailto:accounts@mysukoon.in" className="text-blue-500">accounts@mysukoon.in</a>. We appreciate your understanding and cooperation in helping us allocate resources responsibly and continue our mission of empowering vulnerable communities.
      </p>
    </div>
  );
}

export default Content;
