import { div } from "framer-motion/client";
import React from "react";

function Content() {
    // const SEC = [
    //     {title:"",content:"This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator. "},
    //     {title:"Interpretation and Definitions",content:"Interpretation The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. Definitions For the purposes of this Privacy Policy: * 		Account means a unique account created for You to access our Service or parts of our Service. * 		Affiliate means an entity that controls, is controlled by or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. * 		Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Sukoon Edu Foundation. * 		Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. * 		Country refers to: India * 		Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. * 		Personal Data is any information that relates to an identified or identifiable individual. * 		Service refers to the Website. * 		Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. * 		Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service. * 		Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). * 		Website refers to Sukoon Edu Foundation, accessible from https://sukoon-edu.vercel.app/ * 		You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. "},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},

    // ]
  return (
    <div className="w-[90%] max-w-[1200px] mx-auto py-14">
      {/* <h1 className="text-3xl font-bold mb-4">Refund Policy</h1> */}
      <p className="mb-4">Last updated: January 01, 2025</p>
      <p className="mb-4">
      This refund and cancellation policy outlines how you can cancel or seek a refund for a product / service that you have purchased through the Platform. Under this policy:
Cancellations will only be considered if the request is made 1 days of placing the order.
In case of any refunds approved by SUKOON EDU FOUNDATION, it will take 3 days for the refund to be processed to you and that will be get credited in your source account within 7-10 business days</p>
    </div>
  );
}

export default Content;
