import React from "react";

function Content() {
    // const SEC = [
    //     {title:"",content:"This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator. "},
    //     {title:"Interpretation and Definitions",content:"Interpretation The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. Definitions For the purposes of this Privacy Policy: * 		Account means a unique account created for You to access our Service or parts of our Service. * 		Affiliate means an entity that controls, is controlled by or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. * 		Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Sukoon Edu Foundation. * 		Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. * 		Country refers to: India * 		Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. * 		Personal Data is any information that relates to an identified or identifiable individual. * 		Service refers to the Website. * 		Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. * 		Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service. * 		Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). * 		Website refers to Sukoon Edu Foundation, accessible from https://sukoon-edu.vercel.app/ * 		You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. "},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},
    //     {title:"",content:""},

    // ]
  return (
    <div className="w-[90%] max-w-[1200px] mx-auto py-14">
      {/* <h1 className="text-3xl font-bold mb-4">Terms & Conditions</h1> */}
      <p className="mb-4">Last updated: January 01, 2025</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">1. Acceptance of Terms</h2>
      <p className="mb-4">
        By accessing or using the Sukoon Edu Foundation website, you agree to comply with and be bound by these Terms and Conditions. If you do not agree to these terms, please refrain from using our services.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">2. User Accounts</h2>
      <p className="mb-4">
        To access certain features of our website, you may be required to create a user account. You are responsible for maintaining the confidentiality of your account information and agree to accept responsibility for all activities that occur under your account.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">3. Use of Content</h2>
      <p className="mb-4">
        All content provided on the Sukoon Edu Foundation website is for informational purposes only. You may not modify, reproduce, or distribute any content without our prior written consent.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">4. Privacy Policy</h2>
      <p className="mb-4">
        Your use of our website is also governed by our Privacy Policy. By using our website, you consent to the terms of the Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">5. Termination of Services</h2>
      <p className="mb-4">
        We reserve the right to terminate or suspend your access to our website at any time, without notice, for any reason, including without limitation, breach of these Terms and Conditions.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">6. Changes to Terms</h2>
      <p className="mb-4">
        We reserve the right to modify or replace these Terms and Conditions at any time. Any changes will be effective immediately upon posting. Your continued use of the website after any changes constitutes acceptance of those changes.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Contact Us</h2>
      <p className="mb-4">
        If you have any questions about these Terms and Conditions, you can contact us at <a href="mailto:connect@mysukoon.in" className="text-blue-500">connect@mysukoon.in</a>.
      </p>
    </div>
  );
}

export default Content;
